/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Pertemuan1;

import java.sql.Connection;
import java.sql.SQLException;
import java.util.HashMap;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author Asus
 */
public class ReportDataPembelian extends javax.swing.JFrame {

    /**
     * Creates new form ReportDataPembelian
     */
    public ReportDataPembelian() {
        initComponents();
        showTable();
        hitung();
    }
    
    public void showTable () {
        DefaultTableModel tabel = new DefaultTableModel();
        tabel.addColumn("No_Pembelian");
        tabel.addColumn("Kode_Barang");
        tabel.addColumn("Nama_Barang");
        tabel.addColumn("Jumlah_Beli");
        tabel.addColumn("Tanggal_Beli");
        tabel.addColumn("Kode_Suplier");
        tabel.addColumn("Stok");
        tabel.addColumn("Saham");
        
        try {
            String sql = "SELECT pembelian.No_Pembelian, pembelian.Kode_Barang, pembelian.Nama_Barang, pembelian.Jumlah_Beli, pembelian.Tanggal_Beli, pembelian.Kode_Suplier, barang.Stok, barang.Saham FROM pembelian INNER JOIN barang ON barang.Kode_Barang = pembelian.Kode_Barang;";
            
            java.sql.Connection conn = (Connection)Pertemuan1.Config.configDB();
            java.sql.PreparedStatement pat = conn.prepareStatement(sql);
            java.sql.ResultSet rs = pat.executeQuery(sql);
            
            
            while(rs.next()) {
                tabel.addRow(new Object[] {
                rs.getString(1), rs.getString(2), rs.getString(3),
                rs.getString(4), rs.getString(5), rs.getString(6),
                rs.getString(7), rs.getString(8)
               }); 
                
               jTable1.setModel(tabel);
            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "error");
        }
    }
    
    public void hitung () {
        try {
            String query = "SELECT COUNT(*) AS TotalPembelian, SUM(pembelian.Jumlah_Beli) AS TotalJumlahBeli, SUM(barang.Stok) AS TotalStok, SUM(barang.Saham) AS TotalSaham FROM pembelian INNER JOIN barang ON barang.Kode_Barang = pembelian.Kode_Barang";

            java.sql.Connection conn = (Connection) Pertemuan1.Config.configDB();
            java.sql.PreparedStatement queryPat = conn.prepareStatement(query);
            java.sql.ResultSet rs = queryPat.executeQuery();

            if (rs.next()) {
                int totalPembelian = rs.getInt("TotalPembelian");
                int totalJumlahBeli = rs.getInt("TotalJumlahBeli");
                int totalStok = rs.getInt("TotalStok");
                int totalSaham = rs.getInt("TotalSaham");

                String Pembelian = String.valueOf(totalPembelian); 
                jTextField1.setText(Pembelian);
                String JumlahBeli = String.valueOf(totalJumlahBeli); 
                jTextField2.setText(JumlahBeli);
                String Stok = String.valueOf(totalStok); 
                jTextField3.setText(Stok);
                String Saham = String.valueOf(totalSaham); 
                jTextField4.setText(Saham);
            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "error");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jDateChooser2 = new com.toedter.calendar.JDateChooser();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton2 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("LAPORAN DATA PEMBELIAN");

        jButton1.setText("CARI");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "No_Pembelian", "Kode_Barang", "Nama_Barang", "Jumlah Beli", "Tanggal_Beli", "Kode_Suplier", "Stok", "Saham"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jButton2.setText("CETAK");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel2.setText("Total Pembelian");

        jLabel3.setText("Total Jumlah Beli");

        jLabel4.setText("Total Stok");

        jLabel5.setText("Total Saham");

        jTextField1.setText("jTextField1");

        jTextField2.setText("jTextField2");

        jTextField3.setText("jTextField3");

        jTextField4.setText("jTextField4");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(192, 192, 192))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(252, 252, 252)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(268, 268, 268)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jDateChooser2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 687, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(jButton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(116, 116, 116))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel1)
                .addGap(39, 39, 39)
                .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(jButton1)
                .addGap(9, 9, 9)
                .addComponent(jDateChooser2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(jButton2)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addContainerGap(18, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        DefaultTableModel tabel = (DefaultTableModel) jTable1.getModel();
        tabel.setRowCount(0); // Clearing all rows before adding new ones

        try {
            java.util.Date tgl = jDateChooser1.getDate();
            java.util.Date tgl2 = jDateChooser2.getDate();

            String insertSql = "SELECT pembelian.No_Pembelian, pembelian.Kode_Barang, pembelian.Nama_Barang, pembelian.Jumlah_Beli, pembelian.Tanggal_Beli, pembelian.Kode_Suplier, barang.Stok, barang.Saham FROM pembelian INNER JOIN barang ON barang.Kode_Barang = pembelian.Kode_Barang";

            // Check if both dates are empty or null
            if (tgl == null && tgl2 == null) {
                // No date inputs, so fetch all data
                insertSql = "SELECT pembelian.No_Pembelian, pembelian.Kode_Barang, pembelian.Nama_Barang, pembelian.Jumlah_Beli, pembelian.Tanggal_Beli, pembelian.Kode_Suplier, barang.Stok, barang.Saham FROM pembelian INNER JOIN barang ON barang.Kode_Barang = pembelian.Kode_Barang";
            } else {
                // Date inputs are provided, include date filter
                insertSql += " WHERE pembelian.Tanggal_Beli BETWEEN ? AND ?";
            }

            java.sql.Connection conn = (Connection) Pertemuan1.Config.configDB();
            java.sql.PreparedStatement insertPat = conn.prepareStatement(insertSql);

            // Set parameters only if dates are provided
            if (tgl != null && tgl2 != null) {
                insertPat.setDate(1, new java.sql.Date(tgl.getTime()));
                insertPat.setDate(2, new java.sql.Date(tgl2.getTime()));
            }

            java.sql.ResultSet rs = insertPat.executeQuery();

            while (rs.next()) {
                tabel.addRow(new Object[]{
                    rs.getString(1), rs.getString(2), rs.getString(3),
                    rs.getString(4), rs.getString(5), rs.getString(6),
                    rs.getString(7), rs.getString(8)
                });
            }

            jTable1.setModel(tabel);

        } catch (SQLException e) {
            System.out.println("Error: " + e.getMessage());
        }

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
       try {
            java.util.Date startDate = jDateChooser1.getDate();
            java.util.Date endDate = jDateChooser2.getDate();

            String insertSql = "SELECT pembelian.No_Pembelian, pembelian.Kode_Barang, pembelian.Nama_Barang, pembelian.Jumlah_Beli, pembelian.Tanggal, pembelian.Kode_Suplier, barang.Stok, barang.Saham FROM pembelian INNER JOIN barang ON barang.Kode_Barang = pembelian.Kode_Barang";

            java.sql.Connection conn = (Connection) Pertemuan1.Config.configDB();
            java.sql.PreparedStatement insertPat;

            if (startDate != null && endDate != null) {
                insertSql += " WHERE pembelian.Tanggal_Beli BETWEEN ? AND ?";
                insertPat = conn.prepareStatement(insertSql);

                insertPat.setDate(1, new java.sql.Date(startDate.getTime()));
                insertPat.setDate(2, new java.sql.Date(endDate.getTime()));
            } else {
                insertPat = conn.prepareStatement(insertSql);
            }

            java.sql.ResultSet rs = insertPat.executeQuery();

            if (!rs.isBeforeFirst()) {
                System.out.println("No data found for the given parameters.");
            } else {
                String report = "C:\\Users\\Asus\\Documents\\NetBeansProjects\\JavaProject1\\src\\Pertemuan1\\Laporan\\LaporanPembelian.jrxml";

                JasperReport JRpt = JasperCompileManager.compileReport(report);
                HashMap hash = new HashMap();

                if (startDate != null && endDate != null) {
                    hash.put("startDate", new java.sql.Date(startDate.getTime()));
                    hash.put("endDate", new java.sql.Date(endDate.getTime()));
                }

                JasperPrint JPrint = JasperFillManager.fillReport(JRpt, hash, conn);

                JasperViewer.viewReport(JPrint, false);
            }
        } catch (SQLException | JRException e) {
  
        }

        jDateChooser1.setDate(null);
        jDateChooser2.setDate(null);

    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ReportDataPembelian.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ReportDataPembelian.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ReportDataPembelian.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ReportDataPembelian.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ReportDataPembelian().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private com.toedter.calendar.JDateChooser jDateChooser2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    // End of variables declaration//GEN-END:variables
}
